server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务的微服务名称
  cloud:
    config:
      server:
        git:
          uri:   https://github.com/KunLunLiWuHan/sprincloud-config.git #github上git仓库的名字
          #搜索目录
          search-paths:
            - springcloud-config
      # 读取分支
      label: master

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'