server:
  port: 9528

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway-9528.com
    prefer-ip-address: true


zuul:
#  ignored-services: cloud-payment-service
  prefix: /xiaolun
  ignored-services: "*"
  routes:
    mydept.serviceId: cloud-payment-service
    mydept.path: /mydept/**


